// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rohzyfsnzytxoyaqvtjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvaHp5ZnNuenl0eG95YXF2dGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTYyMTIsImV4cCI6MjA2ODg3MjIxMn0.tOkqJiHcOP1W9O79YTfdvHWi4BweOCIk7N8vD23NZjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});